name: Java CI with Gradle

"on": [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: ['17', '21', '25', '26']

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
          show-progress: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'gradle'
      - name: Cache Spotless p2 data
        uses: actions/cache@v6
        with:
          path: ~/.gradle/p2-data
          key: p2-data-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: p2-data-${{ runner.os }}-
      - name: java -version
        run: java -version
      - name: ./gradlew build
        run: ./gradlew build
